# fly.toml app configuration file generated for libtune-frontend on 2024-12-19T18:24:34+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'libtune'
primary_region = 'gdl'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[http_service.concurrency]
  type = "requests"
  soft_limit = 40
  hard_limit = 100

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
